### ISSUE TITLE
Finalize GroupAggregate showing a negative shared buffer hit

### ISSUE THREAD

**Issue by stephanesql** [dalibo/pev2#240] opened 2020-07-16 08:11 UTC
Hi,
The following plan use a Finalize GroupAggregate indicating a shared buffer hit of 3918, but PEV2 (and explain.dalibo) indicates a negative number of -4730 and shows NaN when converting to MB.

https://explain.dalibo.com/plan/C3f
![image](https://user-images.githubusercontent.com/62691969/87644239-288d1d00-c74c-11ea-8359-f1193eaaca9d.png)

Thanks

**Comment by pgiraud** [comment] 2020-07-16 08:35
Thanks for the report.
Looks like you found a case where the values for buffers are not cumulative (ie. include values for child operations).
I'll have to understand why first in order to find a solution for this.

**Comment by pgiraud** [comment] 2020-07-16 08:45
@stephanesql is it possible for you to share the SQL query corresponding to this plan?
Can you also please tell us which version of postgres you are using?

**Comment by stephanesql** [comment] 2020-07-16 09:14
Postgresql version is  PostgreSQL 12.2 (Ubuntu 12.2-4) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-8ubuntu1) 9.3.0, 64-bit.
I'm using it on windows with WLS 1.

The full query is :
`select contactsourceName, count(*) from dwh.contacts group by contactSourceName ;`

I don't know if it is correlated, but when I add an order by count(*) at the end of the above query, the resulting upper sort does not show the shared buffer hits whereas it is present in the full text plan. You can see it with the query https://explain.dalibo.com/plan/1Te (similare to above plan but with a sort operator for the order by clause).

**Comment by pgiraud** [comment] 2020-07-16 09:50
> the resulting upper sort does not show the shared buffer hits whereas it is present in the full text plan.

This is because PEV2 takes children values into account and computes an exclusive value for buffers of zero for the sort node. This is an expected behavior.

**Comment by Krysztophe** [comment] 2020-07-16 09:57
I can reproduce the behaviour on PG12.3:

```sql
create table contacts (contactSourceName text, filler text) with ( autovacuum_enabled = off) ;
insert into contacts select rpad(chr(64+i)::text,10,'0'), rpad(j::text,500,'0') from generate_series(1,26) i cross join  generate_series(1,3200) j;
SET work_mem TO '4MB';
SET random_page_cost to 4;
SET jit TO off ;
explain (analyze,buffers) select contactsourceName, count(*) from contacts group by contactSourceName order by count(*);
```
Plan : https://explain.dalibo.com/plan/Fdt 
(The problem with Nan is in the above FinalizeGroupAggregate)
```
 Sort  (cost=10279.63..10280.13 rows=200 width=40) (actual time=22.941..22.943 rows=26 loops=1)
   Sort Key: (count(*))
   Sort Method: quicksort  Memory: 27kB
   Buffers: shared hit=3343
   ->  Finalize GroupAggregate  (cost=10221.32..10271.99 rows=200 width=40) (actual time=22.834..22.910 rows=26 loops=1)
         Group Key: contactsourcename
         Buffers: shared hit=3340
         ->  Gather Merge  (cost=10221.32..10267.99 rows=400 width=40) (actual time=22.816..28.865 rows=72 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               Buffers: shared hit=5959
               ->  Sort  (cost=9221.29..9221.79 rows=200 width=40) (actual time=19.011..19.015 rows=24 loops=3)
                     Sort Key: contactsourcename
                     Sort Method: quicksort  Memory: 27kB
                     Worker 0:  Sort Method: quicksort  Memory: 26kB
                     Worker 1:  Sort Method: quicksort  Memory: 26kB
                     Buffers: shared hit=5959
                     ->  Partial HashAggregate  (cost=9211.65..9213.65 rows=200 width=40) (actual time=18.898..18.911 rows=24 loops=3)
                           Group Key: contactsourcename
                           Buffers: shared hit=5943
                           ->  Parallel Seq Scan on contacts  (cost=0.00..8122.10 rows=217910 width=32) (actual time=0.015..10.131 rows=27733 loops=3)
                                 Buffers: shared hit=5943
 Planning Time: 1.386 ms
 Execution Time: 29.191 ms
(24 lignes)
```

**Comment by Krysztophe** [comment] 2020-07-16 10:01
Another extreme example : https://explain.dalibo.com/plan/R1w

**Comment by Krysztophe** [comment] 2020-07-16 11:53
I can reproduce on PG11, and PG10 if I can trigger a ''Gather Merge'' node instead of a simple "Gather".

A bit of googling didn't show anything interesting.

**Comment by Krysztophe** [comment] 2020-07-16 15:34
Problem disappears with `SET parallel_leader_participation TO off`:  https://explain.dalibo.com/plan/97b

**Comment by ioguix** [comment] 2020-07-16 15:37
No, problem is worse with `parallel_leader_participation=off`.

**Comment by ioguix** [comment] 2020-07-16 15:40
I believe Gather Merge only reports its own buffer activity to the upper node, forgetting its workers. So with `parallel_leader_participation=off`, as the Gather Merge node do not work at all, it reports 0 buffers and the Buffers line disapear altogether.

So this is worse.

**Comment by ioguix** [comment] 2020-07-16 15:51
I can now reproduce on my side. I'm investigating the issue in the pgsql code. Will report later.

**Comment by pgiraud** [comment] 2020-07-17 13:58
@stephanesql looks like the current issue is not due to miscalculation on PEV2 side but rather a bug in PostgreSQL.
@ioguix, our own expert, is currently digging PostgreSQL's code and will hopefully come with a patch.

**Comment by ioguix** [comment] 2020-07-18 14:08
hello @stephanesql,

I sent a fix proposal to the pgsql devs.

https://www.postgresql.org/message-id/20200718160206.584532a2%40firost

I don't know if this proposal will be accepted, but no matter what the fix will be, you are the reporter of this bug.

Do you want to appear as reporter? If yes, what name should appear in the commit message?

Regards,

**Comment by stephanesql** [comment] 2020-07-18 18:22
Thanks for your analyze and solution proposal.
It seems the real reporter is you or Krysztophe for this bug. Anyway if you want to add my name as reporter you can use my full name Stéphane Lorek.

**Comment by Krysztophe** [comment] 2020-07-27 09:00
ioguix's patch was pushed on Saturday. It will be included in the next minor release on August 13th for PG 10 and above.

I've tried to reproduce on a PG13 master, and this seems ok now: https://explain.dalibo.com/plan/bpN

**Comment by pgiraud** [comment] 2020-07-27 09:31
Excellent job everyone!
Closing the current issue.

**Closed by pgiraud** 2020-07-27 09:31 UTC
Labels: bug

**Comment by stephanesql** [comment] 2020-07-27 18:58
Thank you all.

**Comment by lrweck** [comment] 2020-08-31 19:33
Hi, 

I think I have the same issue, but with a regular Aggregate. Can someone confirm this is a PG bug, not PEV2?

https://explain.dalibo.com/plan/esX

**Comment by Krysztophe** [comment] 2020-09-01 07:56
@lrweck: I've tried to reproduce, without success yet.

Do you use the last minor version (12.4), with the fix from @ioguix? Can you reproduce the problem on a plan as simple as possible?

**Comment by lrweck** [comment] 2020-09-01 11:47
No, I ran it with 11.5 and 12.1 (I don't have access to a 12.4 machine right now). This is the plan from 12.1: https://explain.dalibo.com/plan/a9y

**Comment by lrweck** [comment] 2020-09-01 12:00
I am using a full join, with aggregates. Here's a plan after running analyze on both tables. It has the query aswell (PG 12.1).
https://explain.dalibo.com/plan/Z30

**Comment by pgiraud** [comment] 2020-09-01 14:44
> It has the query aswell (PG 12.1)

Due to a bug that should be fixed soon, the query SQL is not saved. Sorry.

I suspect that you're facing the postgresql bug that has been fixed with the latest minor versions released mid august.

**Comment by lrweck** [comment] 2020-09-01 16:58
> > It has the query aswell (PG 12.1)
> 
> Due to a bug that should be fixed soon, the query SQL is not saved. Sorry.
> 
> I suspect that you're facing the postgresql bug that has been fixed with the latest minor versions released mid august.

No problem.

Here's the query, btw

```
SELECT   Coalesce(T1.F1,T2.F1) AS F1, 
         Coalesce(T1.F2,T2.F2) AS F2, 
         T1.F3, 
         T2.F4 
FROM     ((SELECT   F1, 
                    F2, 
                    Sum(iF3) AS F3 
           FROM     (SELECT T1.CarCod AS F1, 
                            T2.CarNom    AS F2, 
                            T1.DevSal AS iF3 
                     FROM   (Devedor T1 
                             INNER JOIN Carteira T2 
                               ON T2.CarCod = T1.CarCod) 
                     WHERE  (T1.CarCod > 0)
                            AND (T1.DevSal > 0)) A 
           GROUP BY F1, 
                    F2) T1 
          FULL JOIN (SELECT   F1, 
                              F2, 
                              Count(iF4) AS F4 
                     FROM     (SELECT T1.CarCod AS F1, 
                                      T2.CarNom    AS F2, 
                                      T1.DevCod    AS iF4 
                               FROM   (Devedor T1 
                                       INNER JOIN Carteira T2 
                                         ON T2.CarCod = T1.CarCod) 
                               WHERE  (T1.CarCod > 0) ) A 
                     GROUP BY F1, 
                              F2) T2 
            ON (T2.F1 = T1.F1 
                AND T2.F2 = T1.F2)) 
ORDER BY F1, 
         F2 
```
